a=int(input("Enter a number: "))
b=int(input("Enter another number: "))
c=int(input("Enter a third number: "))
print(a+b+c)
print(a*b*c)
print(a/b)
print(a%b)
print(a**b)
print(a//b)
print(a-b-c)
print(a-b*c)
print(a-b/c)
print(a-b%c)
print(a==b)
print(a!=b)
print(a>b)
print(a<b)
print(a>=b)
print(a<=b)
num=int(input("Enter a number: "))
if(num%2==0):
    print("Even")
else:
    print("Odd")
